channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - cudatoolkit=10.1
  - pytorch>=1.3
  - torchvision
  - pillow<7
  - trimesh=3.9
  - networkx=2.2
  - pip
  - pip:
      - termcolor~=1.1
      - opencv-python~=4.5
      - tensorboard~=2.4
      - plyfile~=0.7
      - matplotlib
      - open3d~=0.12